services:
  web:
    build: .
    command: gunicorn ece_booking.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - DOMAIN=${DOMAIN}
      - TU_REST_API=${TU_REST_API}
    ports:
      - "8001:8000"
    networks:
      - default
      - server_default

networks:
  server_default:
    external: true

volumes:
  static_volume:
