services:
  db:
    image: postgres:16-alpine
    container_name: ece-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # ใส่รหัสผ่านเริ่มต้นไว้ให้เลยครับ
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ece-network
    labels:
      - "com.ece.allow_logs=true"

  web:
    build: .
    container_name: ece-web
    command: gunicorn ece_booking.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=ece_booking.settings
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ece-network
    labels:
      - "com.ece.allow_logs=true"

  nginx:
    image: nginx:1.25-alpine
    container_name: ece-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8081:80
    depends_on:
      - web
    networks:
      - ece-network
    labels:
      - "com.ece.allow_logs=true"

  dozzle:
    image: amir20/dozzle:latest
    container_name: ece-dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_FILTER=label=com.ece.allow_logs=true
    ports:
      - 8888:8080
    networks:
      - ece-network

networks:
  ece-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
