services:
  web:
    build: .
    command: gunicorn ece_booking.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    ports:
      - "8001:8000"
    networks:
      - default
      - server_default

networks:
  server_default:
    external: true

volumes:
  static_volume:
