# Generated by Django 5.1.15 on 2026-04-28 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booker_id', models.CharField(max_length=100)),
                ('booker_name', models.CharField(blank=True, max_length=200)),
                ('purpose_type', models.CharField(choices=[('COURSE', 'สอนวิชา'), ('TRAINING', 'ฝึกอบรม')], default='COURSE', max_length=20)),
                ('course_code', models.CharField(blank=True, max_length=50)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('training_title', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurring_pattern', models.JSONField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'รอการอนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ปฏิเสธ'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approval_by', models.CharField(blank=True, max_length=100)),
                ('approval_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teams_service_url', models.CharField(blank=True, default='', max_length=500)),
                ('teams_conversation_id', models.CharField(blank=True, default='', max_length=500)),
                ('teams_activity_id', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MEETING', 'ห้องประชุม'), ('LECTURE', 'ห้องเรียน')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tu_uid', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('LECTURER', 'Lecturer')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='booking.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room'),
        ),
        migrations.CreateModel(
            name='BlackoutPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackout_periods', to='booking.room')),
            ],
        ),
    ]
