# Generated by Django 5.1.15 on 2026-04-28 16:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_blackoutperiod_bookinglog_tuuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tu_uid', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('LECTURER', 'Lecturer')], default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TuUser',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_room_booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booker_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='teams_activity_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='teams_conversation_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='teams_service_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blackoutperiod',
            name='created_by',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blackoutperiod',
            name='reason',
            field=models.TextField(blank=True, default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blackoutperiod',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackout_periods', to='booking.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='approval_by',
            field=models.CharField(blank=True, default='placeholder', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booker_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_code',
            field=models.CharField(blank=True, default='placeholder', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_name',
            field=models.CharField(blank=True, default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose_type',
            field=models.CharField(choices=[('COURSE', 'สอนวิชา'), ('TRAINING', 'ฝึกอบรม')], default='COURSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอการอนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ปฏิเสธ'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='training_title',
            field=models.CharField(blank=True, default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='actor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('MEETING', 'ห้องประชุม'), ('LECTURE', 'ห้องเรียน')], max_length=20),
        ),
    ]
