# Generated by Django 5.2.7 on 2026-04-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_userprofile_delete_tuuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='training_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
