# Generated by Django 5.2.12 on 2026-05-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking",
            "0004_alter_booking_course_code_alter_booking_course_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BACHELOR", "ปริญญาตรีภาคปกติ"),
                    ("MASTER", "ปริญญาโท"),
                    ("TEP_TEPE", "TEP-TEPE"),
                    ("TU_PINE", "TU-PINE"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
