# Generated by hand to standardize statuses, roles, actions, and days_of_week to uppercase and proper types

from django.db import migrations

def standardize_data(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    UserProfile = apps.get_model('booking', 'UserProfile')
    BookingLog = apps.get_model('booking', 'BookingLog')

    # Update Booking status
    for b in Booking.objects.all():
        if b.status:
            b.status = b.status.upper()
        if b.days_of_week:
            try:
                b.days_of_week = [int(d) for d in b.days_of_week]
            except Exception:
                pass
        b.save()

    # Update UserProfile role
    for up in UserProfile.objects.all():
        if up.role:
            up.role = up.role.upper()
            up.save()

    # Update BookingLog action
    for bl in BookingLog.objects.all():
        if bl.action:
            bl.action = bl.action.upper()
            bl.save()

def reverse_standardize_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_program'),
    ]

    operations = [
        migrations.RunPython(standardize_data, reverse_standardize_data),
    ]
